app/config/routes.rb
Rails.application.routes.draw do
  resource :sessions, only: [:new, :create, :destroy]
  # PAGE ROUTES
  get '/' => 'home#index', as: :root
  # ROUTE for SEARCH
  get 'product_search' => 'product_search#index', as: :product_search
  get 'product_search/find' => 'product_search#index'
  post 'product_search/find' => 'product_search#find', as: :find

  # USER ROUTES
  get 'users/' => 'users#index'
  get 'users/new' => 'users#new', as: :new_user
  get 'users/:id' => 'users#show', as: :user
  post 'users/' => 'users#create'
  get 'users/:id/edit' => 'users#edit', as: :edit_user
  patch 'users/:id' => 'users#update'
  delete 'users/:id' => 'users#destroy'

  # MAKE UP CASE ROUTES
  # get 'makeupcases/' => 'makeupcases#index'
  # get 'makeupcases/new' => 'makeupcases#new', as: :new_makeupcase
  # get 'makeupcases/:id' => 'makeupcases#show', as: :makeupcase
  # post 'makeupcases/' => 'makeupcases#create'
  # get 'makeupcases/:id/edit' => 'makeupcases#edit', as: :edit_makeupcase
  # patch 'makeupcases/:id' => 'makeupcases#update'
  # delete 'makeupcases/:id' => 'makeupcases#destroy'

  # PRODUCT ROUTES
  get 'products/' => 'products#index'
  get 'products/new' => 'products#new', as: :new_product
  get 'products/add_to_case' => 'products#add_to_case', as: :add_to_case
  get 'products/:id' => 'products#show', as: :product
  post 'products/' => 'products#create'
  get 'products/:id/edit' => 'products#edit', as: :edit_product
  patch 'products/:id' => 'products#update'
  delete 'products/:id' => 'products#destroy'

end

app/app/models/product.rb
class Product
  include Mongoid::Document
  field :brand, type: String
  field :product_name, type: String
  field :factual_id, type: String
  field :size, type: String
  field :upc, type: String
  field :ean13, type: String
  field :upc_e, type: String
  field :category, type: String
  field :avg_price, type: Float
  field :manufacturer, type: String
  field :ingredients, type: String
  field :short_description, type: String
  field :full_description, type: String
  field :image_urls, type: Array, default: [1,2,3,4]
  field :date_first_use, type: Date
  field :date_expired, type: Date
  field :like_or_not, type: Mongoid::Boolean
  field :review, type: String
  field :amazon_link, type: String
  field :walmart_link, type: String
  field :buycom_link, type: String

  belongs_to :user
end

app/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :make_sure_logged_in, only: [:create, :edit, :update, :new, :destroy]
  def index
    @products = Product.where('user_id' => current_user.id.to_s)
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end  

  def create
    @product = Product.new(params.require(:product).permit(:brand, :product_name, :size, :upc, :ean13, :upc_e, :category, :avg_price, :manufacturer, :ingredients, :short_description, :full_description, :image_urls, :date_first_use, :expiration_date, :like_or_not, :review, :user_id))
    @product.user_id = current_user.id.to_s
    # IMAGE ISSUE WITH ADDING OBJECT INTO DATABASE NOT FIXED.
    if params[:product]['image_urls']
      params[:product]['image_urls'].each_with_index do |i,index|
        @product.image_urls[index] = i
      end
    end
    if @product.save
      redirect_to products_path
    else
      redirect_to new_product_path
    end
  end
  # Add products into your case from search query
  def add_to_case
    raise respond_to.inspect
    @select_product = params[:select_product]
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params.require(:product).permit(:brand, :product_name, :size, :avg_price, :date_first_use, :date_expired, :like_or_not, :review))
      redirect_to products_path
    else
      render 'edit'
    end
    # FIXING IMAGE PROBLEM _ NOT RESOLVED
    # if @products.image_urls
    #   @product.image_urls.each_with_index do |i,index|
    #     @product.image_urls[index] = i
    #   end
    # end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end
  
  private
    def make_sure_logged_in
      if !current_user 
        redirect_to new_sessions_path
      end
    end
end

app/app/views/products/_form.html.erb
<div class="row">
  <div id="signin" class="col-sm-6 col-sm-offset-3">
    <%= bootstrap_form_for(@product) do |f| %>
      <%= f.text_field :brand%>
      <%= f.text_field :product_name%>
      <%= f.text_field :size%>
      <%= f.text_field :upc%>
      <%= f.text_field :ean13%>
      <%= f.text_field :upc_e%>
      <%= f.text_field :category%>
      <%= f.text_field :avg_price%>
      <%= f.text_field :manufacturer%>
      <%= f.text_field :ingredients%>
      <%= f.text_field :short_description%>
      <%= f.text_field :full_description%>
      <%= f.text_field :image_urls%>
      <%= f.date_field :date_first_use%>
      <%= f.date_field :date_expired%>
      <%= f.check_box :like_or_not, label: 'Like?'%>
      <%= f.text_area :review%>

      
      <%= f.submit 'Create my account', :class => 'btn btn-primary btn-lg btn-block'%>
    <% end %>
  </div>
</div>

app/app/views/products/edit.html.erb
<div class="row">
  <div class="col-sm-4 col-sm-offset-4">
    <h1>Edit product</h1>
  </div>
</div>

<div class="row">
  <div id="signin" class="col-sm-6 col-sm-offset-3">
    <%= bootstrap_form_for(@product) do |f| %>
      <%= f.text_field :brand%>
      <%= f.text_field :product_name%>
      <%= f.text_field :size%>
      <%= f.text_field :avg_price%>
      <%= f.date_field :date_first_use%>
      <%= f.date_field :date_expired%>
      <%= f.check_box :like_or_not, label: 'Like?'%>
      <%= f.text_area :review%>
      <%= f.submit 'Make changes', :class => 'btn btn-primary btn-lg btn-block'%>
    <% end %>
  </div>
</div>

app/app/views/products/index.html.erb
<div class="row">
  <div class="col-sm-4 col-sm-offset-4">
    <h1>Your make up case</h1>
  </div>
</div>
<div class="row">
  <div id="signin" class="col-sm-10 col-sm-offset-1">
    <% if @products %>
      <div class="table-responsive">
        <table class="table table-hover">
          <tr>
            <th>Brand</th>
            <th>Name</th>
            <th>Size</th>
            <th>Category</th>
            <th>Ave Price</th>
            <th>Manufacturer</th>
            <th>Ingredients</th>
            <th>Short Description</th>
            <th>Opened Date</th>
            <th>Expiration Date</th>
            <th>Like or Not</th>
            <th>Review</th>
            <th>More Info</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
              <% @products.each do |p| %>
                <tr>
                  <td><%= p.brand %></td>
                  <td><%= p.product_name %></td>
                  <td><%= p.upc_e %></td>
                  <td><%= p.category %></td>
                  <td><%= p.avg_price %></td>
                  <td><%= p.manufacturer %></td>
                  <td><%= p.ingredients %></td>
                  <td><%= p.short_description %></td>
                  <td><%= p.date_first_use %></td>
                  <td><%= p.date_expired %></td>
                  <td><%= p.like_or_not %></td>
                  <td><%= p.review %></td>
                  <td><%= link_to '+', product_path(p) %></td>
                  <td><%= link_to 'Edit', edit_product_path(p) %></td>
                  <td><%= link_to 'X', p, method: :delete, data: {confirm: 'Are you sure?'} %></td>
                </tr>
              <% end %>
        </table>
      </div>
    <% else %>
      <div class="row">
        <div class="col-sm-4 col-sm-offset-4">
          <h3>No product available. Add more here.</h3>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/app/views/products/new.html.erb
<div class="row">
  <div class="col-sm-4 col-sm-offset-4">
    <h1>Add new product</h1>
  </div>
</div>
<%= render 'form' %>

app/app/views/products/show.html.erb
<div class="row">
  <div class="col-sm-4 col-sm-offset-4">
    <h1>Product detail</h1>
  </div>
</div>
<div class="table-responsive">
  <table class="table table-hover">
    <tr>
      <th>Brand</th>
      <th>Name</th>
      <th>Size</th>
      <th>UPC</th>
      <th>EAN 13</th>
      <th>UPC e</th>
      <th>Category</th>
      <th>Ave Price</th>
      <th>Manufacturer</th>
      <th>Ingredients</th>
      <th>Short Description</th>
      <th>Full Description</th>
      <th>Image URLS</th>
      <th>Opened Date</th>
      <th>Expiration Date</th>
      <th>Like or Not</th>
      <th>Review</th>
      <th>Belongs to</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
        <tr>
          <td><%= @product.brand %></td>
          <td><%= @product.product_name %></td>
          <td><%= @product.size %></td>
          <td><%= @product.upc %></td>
          <td><%= @product.ean13 %></td>
          <td><%= @product.upc_e %></td>
          <td><%= @product.category %></td>
          <td><%= @product.avg_price %></td>
          <td><%= @product.manufacturer %></td>
          <td><%= @product.ingredients %></td>
          <td><%= @product.short_description %></td>
          <td><%= @product.full_description %></td>
          <td>
            <!-- Check make sure image is availble to show, otherwise don't -->
            <% @product.image_urls.each do |image| %>



              <%= image_tag(image, :class => "img-rounded", :height => "50") %>
            <% end %>
          </td>
          <td><%= @product.date_first_use %></td>
          <td><%= @product.date_expired %></td>
          <td><%= @product.like_or_not %></td>
          <td><%= @product.review %></td>
          <td><%= @product.user.name if @product.user %></td>
          <td><%= link_to 'Edit', edit_product_path(@product) %></td>
          <td><%= link_to 'X', @product, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
  </table>
</div>