app/config/routes.rb
Rails.application.routes.draw do
  resource :sessions, only: [:new, :create, :destroy]
  # PAGE ROUTES
  get '/' => 'home#index', as: :root
  # ROUTE for SEARCH
  get 'product_search' => 'product_search#index', as: :product_search
  get 'product_search/find' => 'product_search#index'
  post 'product_search/find' => 'product_search#find', as: :find

  # USER ROUTES
  get 'users/' => 'users#index'
  get 'users/new' => 'users#new', as: :new_user
  get 'users/:id' => 'users#show', as: :user
  post 'users/' => 'users#create'
  get 'users/:id/edit' => 'users#edit', as: :edit_user
  patch 'users/:id' => 'users#update'
  delete 'users/:id' => 'users#destroy'

  # MAKE UP CASE ROUTES
  # get 'makeupcases/' => 'makeupcases#index'
  # get 'makeupcases/new' => 'makeupcases#new', as: :new_makeupcase
  # get 'makeupcases/:id' => 'makeupcases#show', as: :makeupcase
  # post 'makeupcases/' => 'makeupcases#create'
  # get 'makeupcases/:id/edit' => 'makeupcases#edit', as: :edit_makeupcase
  # patch 'makeupcases/:id' => 'makeupcases#update'
  # delete 'makeupcases/:id' => 'makeupcases#destroy'

  # PRODUCT ROUTES
  get 'products/' => 'products#index'
  get 'products/new' => 'products#new', as: :new_product
  get 'products/add_to_case' => 'products#add_to_case', as: :add_to_case
  get 'products/:id' => 'products#show', as: :product
  post 'products/' => 'products#create'
  get 'products/:id/edit' => 'products#edit', as: :edit_product
  patch 'products/:id' => 'products#update'
  delete 'products/:id' => 'products#destroy'

end

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head class="full">
  <title>Bc</title>
  <%= stylesheet_link_tag    'application'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.0/angular.min.js"></script>
  <script src="https://cdn.firebase.com/js/client/1.0.21/firebase.js"></script>
  <script src="https://cdn.firebase.com/libs/angularfire/0.6.0/angularfire.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
</head>
<body>
<nav id="navbar" class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><%= image_tag("logo.png", :height => "50") %></a>
      <a class="navbar-brand" href="/">my<strong>beauty</strong>case</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

      </ul>
      <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
          <li><a href="/">Hi, <%=current_user.name%>!</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-cog"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%=link_to 'Sign out', sessions_path, method: :delete%></li>
              <li><%=link_to 'Add product', new_product_path%></li>
              <li><%=link_to 'Show product', products_path%></li>
              <li><%=link_to 'Show users', users_path%></li>
              <li class="divider"></li>
              <li><a href="#">Profile</a></li>
              <li><a href="#">Help</a></li>
              <li><%=link_to 'Delete account', user_path(current_user), {method: :delete, confirm: "Are you really really really sure bud?"} %></li>
            </ul>
          </li>
        <% else %>
          <li><%=link_to 'Log in', new_sessions_path if !@is_login %></li>
          <li><%=link_to 'Sign Up', new_user_path if !@is_signup%></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!-- SEARCH BAR -->
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= render './product_search/search' %>
  </div>
</div>

<%= yield %>

</body>
</html>