app/config/routes.rb
Rails.application.routes.draw do
  resource :sessions, only: [:new, :create, :destroy]
  # PAGE ROUTES
  get '/' => 'home#index', as: :root
  # ROUTE for SEARCH
  get 'product_search' => 'product_search#index', as: :product_search
  get 'product_search/find' => 'product_search#index'
  post 'product_search/find' => 'product_search#find', as: :find

  # USER ROUTES
  get 'users/' => 'users#index'
  get 'users/new' => 'users#new', as: :new_user
  get 'users/:id' => 'users#show', as: :user
  post 'users/' => 'users#create'
  get 'users/:id/edit' => 'users#edit', as: :edit_user
  patch 'users/:id' => 'users#update'
  delete 'users/:id' => 'users#destroy'

  # MAKE UP CASE ROUTES
  # get 'makeupcases/' => 'makeupcases#index'
  # get 'makeupcases/new' => 'makeupcases#new', as: :new_makeupcase
  # get 'makeupcases/:id' => 'makeupcases#show', as: :makeupcase
  # post 'makeupcases/' => 'makeupcases#create'
  # get 'makeupcases/:id/edit' => 'makeupcases#edit', as: :edit_makeupcase
  # patch 'makeupcases/:id' => 'makeupcases#update'
  # delete 'makeupcases/:id' => 'makeupcases#destroy'

  # PRODUCT ROUTES
  get 'products/' => 'products#index'
  get 'products/new' => 'products#new', as: :new_product
  get 'products/add_to_case' => 'products#add_to_case', as: :add_to_case
  get 'products/:id' => 'products#show', as: :product
  post 'products/' => 'products#create'
  get 'products/:id/edit' => 'products#edit', as: :edit_product
  patch 'products/:id' => 'products#update'
  delete 'products/:id' => 'products#destroy'

end

app/app/controllers/product_search_controller.rb
class ProductSearchController < ApplicationController
  def index
  end
  def find
    # pull the search text from the search bar to start our query to factual server
    @products = factual.table("products-cpg").search(params[:query]).rows
    # CROSS WALK LOOKUP API CALL FOR EACH PRODUCTS FOR LINKS TO AMAZON
    # AND ONLINE MERCHANDISERS
    # @products_crosswalk = []
    # @products.each do |p|
    #   @products_crosswalk.push(factual.table("products-crosswalk").search(p['factual_id']).rows)
    # end
    # raise @products_crosswalk.inspect
  end
end

app/app/views/product_search/_add_to_case.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
</div>
<div class="modal-body">
asdfsdfASdfASDFASDf
as
df
asdf
asd
fas
df
</div>
<div class="modal-footer">
  <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  <button class="btn btn-primary">Save changes</button>
</div>

app/app/views/product_search/_search.html.erb
<%= form_tag(find_path, method: :post) do %>
  <%= text_field_tag(:query, params[:query], :class => 'form-control input-lg', :placeholder => 'type your favorite product here')%>
<% end %>

app/app/views/product_search/find.html.erb
<div class="row">
  <div id="signin" class="col-sm-10 col-sm-offset-1">
    <h1>Products Factual API Test</h1>
      <table class="table table-condensed table-hover">
        <tr>
          <th>Brand</th>
          <th>Name</th>
          <th>Size</th>
          <th>Ave Price</th>
          <th>Pictures</th>
          <th></th>
        </tr>
        <% @products.each_with_index do |r,index| %>
          <tr>
            <% if r['brand'] %>
              <td class="vert-align"><%= r['brand'] %></td>
            <% else %>
              <td>-</td>
            <% end %>
            <% if r['product_name'] %>
              <td class="vert-align"><%= r['product_name'] %></td>
            <% else %>
              <td>-</td>
            <% end %>
            <% if r['size'] %>
              <td class="vert-align"><%= r['size'][0] %></td>
            <% else %>
              <td>-</td>
            <% end %>
            <% if r['avg_price'] %>
              <td class="vert-align">$<%= r['avg_price'] %></td>
            <% else %>
              <td>-</td>
            <% end %>
              <% if r['image_urls'] %>
              <td class="vert-align"><%= image_tag(r['image_urls'].first, :class => "img-rounded", :height => "50") %></td>
            <% else %>
              <td>-</td>
            <% end %>
            <td class="vert-align">
              <div class="btn-group">
                
                <%= button_to('Add', products_path(:product => r), :controller => 'products_controller', :action => 'add_to_case', :data => {:id => index, :factual_id => r['factual_id'], :toggle=>'modal', :target => '.bs-example-modal-sm'}, :class => "btn btn-primary") %>
                <%= button_to('Adda', add_to_case_path(:product => r), :controller => 'products_controller', :action => 'new', :data => {:id => index, :factual_id => r['factual_id'], :toggle=>'modal', :target => '.bs-example-modal-sm'}, :class => "btn btn-primary") %>

                <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-sm">Small modal</button>
              </div>
            </td>
          </tr>
        <% end %>
      </table>
  </div>
</div>

<!-- PARTIAL MODAL-->
<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <%= render 'add_to_case', modal: true %>
    </div>
  </div>
</div>